### ISSUE TITLE
openslide could not be imported 

### ISSUE THREAD

**Issue by marshelma** [openslide/openslide-winbuild#21]
windows 10, anaconda3 64bit, python2.7.15,openslide-win64-20171122 and openslide-python1.1.1 from pip

trying to import openslide, give the following error:

The procedure entry point iconv could not be located in the dynamic link library
C:\Anaconda2\Packages\openslide\bin\libxml2-2.dll

The procedure entry point iconv could not be located in the dynamic link library
C:\Anaconda2\Packages\openslide\bin\llibintl-8.dll

**Comment by QianyeYang** [comment]
windows 10, anaconda3 64 bit, python 3.6.5
I just moved the environment variable of the path of the ..\openslide....\bin to the top of the list. The problem was solved.

**Comment by BeibinLi** [comment]
I have the same problem, and I have tried to move the path to the top in environment variables. However, the problem still exists. 

Any comments?

**Comment by bgilbert** [comment]
Anaconda ships different versions of some of the libraries included in the OpenSlide Windows distribution.  If you try to use both sets of libraries, they may conflict.  This shouldn't happen if you use the OpenSlide Windows distribution with vanilla Python, or if you obtain OpenSlide from the same distribution as your other libraries.
